BlessedHub/Controllers/PrayerTimings1Controller.cs
  using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BlessedHub.Core.RepositoriesInterfaces;
using BlessedHub.Models;
using BlessedHub.ViewModels;

namespace BlessedHub.Controllers
{
    
    public class PrayerTimings1Controller : Controller
    {
        private TheBlessedHubEntities db = new TheBlessedHubEntities();
        private readonly IUnitOfWork _unitOfWork;
        public PrayerTimings1Controller(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        // GET: PrayerTimings1
        public ActionResult Index()
        {
            return View(_unitOfWork.prayerTimingRepository.GetPrayerTimings().ToList());

        }
        // GET: PrayerTimings1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var prayerTiming = _unitOfWork.prayerTimingRepository.GetPrayerTiming(id);
            if (prayerTiming == null)
            {
                return HttpNotFound();
            }
            var ptVM = Mapper.Map<PrayerTimingVM>(prayerTiming);
            return View(ptVM);
        }
        // GET: PrayerTimings1/Create
        public ActionResult Create()
        {
            ViewBag.MasjidId = new SelectList(db.MasjidDetails, "Id", "MasjidName");
            return View();
        }
        // POST: PrayerTimings1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,MasjidId,CalendarPicURL,DateAdded,DateUpdated")] PrayerTiming prayerTiming)
        {
            if (ModelState.IsValid)
            {
                db.PrayerTimings.Add(prayerTiming);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MasjidId = new SelectList(db.MasjidDetails, "Id", "MasjidName", prayerTiming.MasjidId);
            return View(prayerTiming);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePrayerTimings(PrayerTimingVM vmModel)
        {
            string filePath = string.Empty;
            string fileContentType = string.Empty;
            string filename = string.Empty;

            try
            {
                // Verification
                if (ModelState.IsValid)
                {
                    // Converting to bytes.
                    byte[] uploadedFile = new byte[vmModel.FileAttach.InputStream.Length];
                    vmModel.FileAttach.InputStream.Read(uploadedFile, 0, uploadedFile.Length);

                    // Initialization.
                    fileContentType = vmModel.FileAttach.ContentType;

                    filename = vmModel.MasjidId + ".png";

                    //string folderPath = "~/Images/PrayerTimings/";
                    //this.WriteBytesToFile(this.Server.MapPath(folderPath), uploadedFile, filename);

                    //https://member3-3.smarterasp.net/cp/filemanager?d=h:/root/home/shahbazali-001/www/theblessedhub/images/prayertimings/
                    string folderPath = "/Images/PrayerTimings/";
                    //filePath = Path.Combine(Server.MapPath(folderPath), filename);
                    this.WriteBytesToFile(this.Server.MapPath(folderPath), uploadedFile, filename);
                    filePath = folderPath + filename;                                     
                }
                //Mapper.Map(vmModel,test);

                var prayerTiming = new PrayerTiming
                {
                    MasjidId = vmModel.MasjidId,
                    DateAdded = vmModel.DateAdded,
                    DateUpdated = vmModel.DateUpdated,
                    CalendarPicURL = filePath



                };

                if (ModelState.IsValid)
                {

                    var prytime = _unitOfWork.prayerTimingRepository.GetMasjidByName(prayerTiming.CalendarPicURL);

                    if(prytime ==null)
                    {
                        _unitOfWork.prayerTimingRepository.Add(prayerTiming);
                        _unitOfWork.Complete();

                    }

                   
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                // Info
                Console.Write(ex);
            }
            return View("Index");
        }
        private void WriteBytesToFile(string rootFolderPath, byte[] fileBytes, string filename)
        {
            try
            {
                // Verification.
                if (!Directory.Exists(rootFolderPath))
                {
                    // Initialization.
                    string fullFolderPath = rootFolderPath;

                    // Settings.
                    string folderPath = new Uri(fullFolderPath).LocalPath;

                    // Create.
                    Directory.CreateDirectory(folderPath);
                }

                // Initialization.                
                string fullFilePath = rootFolderPath + filename;

                // Create.
                FileStream fs = System.IO.File.Create(fullFilePath);

                // Close.
                fs.Flush();
                fs.Dispose();
                fs.Close();

                // Write Stream.
                BinaryWriter sw = new BinaryWriter(new FileStream(fullFilePath, FileMode.Create, FileAccess.Write));

                // Write to file.
                sw.Write(fileBytes);

                // Closing.
                sw.Flush();
                sw.Dispose();
                sw.Close();
            }
            catch (Exception ex)
            {
                // Info.
                throw ex;
            }
        }
        // GET: PrayerTimings1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrayerTiming prayerTiming = _unitOfWork.prayerTimingRepository.GetPrayerTiming(id);
            if (prayerTiming == null)
            {
                return HttpNotFound();
            }
            var ptVM = Mapper.Map<PrayerTimingVM>(prayerTiming);
            ViewBag.MasjidId = new SelectList(db.MasjidDetails, "Id", "MasjidName", prayerTiming.MasjidId);
            return View(ptVM);
        }
        // POST: PrayerTimings1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MasjidId,CalendarPicURL,DateAdded,DateUpdated")] PrayerTiming prayerTiming)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.DbStateModified(prayerTiming);
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            ViewBag.MasjidId = new SelectList(db.MasjidDetails, "Id", "MasjidName", prayerTiming.MasjidId);
            return View(prayerTiming);
        }
        // GET: PrayerTimings1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var prayerTiming = _unitOfWork.prayerTimingRepository.GetPrayerTiming(id);
            if (prayerTiming == null)
            {
                return HttpNotFound();
            }
            var ptVM = Mapper.Map<PrayerTimingVM>(prayerTiming);
            return View(ptVM);
        }
        // POST: PrayerTimings1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PrayerTiming prayerTiming = _unitOfWork.prayerTimingRepository.GetPrayerTiming(id);
            _unitOfWork.prayerTimingRepository.Remove(prayerTiming);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlessedHub/Views/PrayerTimings1/Create.cshtml
@model BlessedHub.ViewModels.PrayerTimingVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm("CreatePrayerTimings", "PrayerTimings1", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>PrayerTiming</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MasjidId, "MasjidId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MasjidId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MasjidId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CalendarPicURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CalendarPicURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CalendarPicURL, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-push-2">
            <div class="input-group">
                <span class="input-group-btn">
                    <span class="btn btn-default btn-file">
                        Browse&hellip;
                        @Html.TextBoxFor(m => m.FileAttach, new { type = "file", placeholder = Html.DisplayNameFor(m => m.FileAttach), @class = "form-control" })
                    </span>
                    @*<input type="text" class="form-control" readonly>*@
                </span>

            </div>
            @Html.ValidationMessageFor(m => m.FileAttach, "", new { @class = "text-danger custom-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateUpdated, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateUpdated, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlessedHub/Views/PrayerTimings1/Delete.cshtml
@model BlessedHub.ViewModels.PrayerTimingVM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PrayerTiming</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CalendarPicURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CalendarPicURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MasjidDetail.MasjidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MasjidDetail.MasjidName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlessedHub/Views/PrayerTimings1/Details.cshtml
@model BlessedHub.ViewModels.PrayerTimingVM

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div>
    <h4>PrayerTiming</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CalendarPicURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CalendarPicURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MasjidDetail.MasjidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MasjidDetail.MasjidName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlessedHub/Views/PrayerTimings1/Edit.cshtml
@model BlessedHub.ViewModels.PrayerTimingVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PrayerTiming</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.MasjidId, "MasjidId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasjidId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MasjidId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CalendarPicURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CalendarPicURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CalendarPicURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateUpdated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateUpdated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlessedHub/Views/PrayerTimings1/Index.cshtml
@model IEnumerable<BlessedHub.Models.PrayerTiming>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CalendarPicURL)
        </th>
        <th>Time Table</th>
        <th>
            @Html.DisplayNameFor(model => model.DateAdded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MasjidDetail.MasjidName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CalendarPicURL)
        </td>
        <td>  <img src='@item.CalendarPicURL' widtd="100" height="100" /></td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUpdated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MasjidDetail.MasjidName)
        </td>
        <td>
          
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>